### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by luxville** [tuukkalai/CandyTracker#1]
Sovellus näyttää Herokussa hyvältä. Toimintoja on vielä rajallisesti, mutta kaikki toteutettu vaikutti toimivan oikein ainakin normaaleilla syötteillä. Saman käyttäjätunnuksen luominen kahdesti ei onnistunut ja salasanan tarkistus toimi. Makeisten lisääminen tietokantaan edellyttää kaikkien tietojen antamista, mutta tallennetut tiedot näkyvät myös toisella käyttäjätunnuksella ja toisella laitteella kirjauduttaessa, joten tallennus tietokantaan toimii. Ohjelmassa ei ole ainakaan vielä käytössä mahdollisuutta poistaa makeisia tai käyttäjätilejä.

Sovelluksen käyttö on helppoa selkeän ulkoasun vuoksi, näytön skaalautuvuus kännykän ruudulta kuitenkin jättää vähän toivomisen varaa, kun näytön ollessa pystyasennossa päivyri pitää jokaisen päivämäärän näyttämistä tärkeämpänä kuin varsinaisia kuvaajia. Samoin kännykällä näytön ollessa vaaka-asennossa päivämäärävalintaruutu ei näy kokonaisuudessaan. 

Mielenkiintoisia lisätoimintoja nykyiseen versioon olisivat tiedot siitä, mistä makeisten määrä koostuu ja historiatietojen tutkiminen ainakin vähän pidemmältä ajalta, kun kerran kalenteri antaa siihen mahdollisuuden.

Ilmeisesti sovelluksessa olevat osat kyselyistä ja viesteistä vaikuttavat olevan jäänteitä kurssimateriaalin esimerkeistä.

Sovelluksen koodi on jaettu rakenteellisesti toiminnallisuuksia ja tietokantatauluja mukailevasti nimettyihin tiedostoihin, joten tarvittavat toiminnot löytyvät helposti. Tietokantatauluja näyttäisi tässä vaiheessa olevan varsinaisen karkkikalenterin käytössä 3 kappaletta, joista yksi on liitostaulu. Readme-tiedoston perusteella toimintoja on tulossa vielä lisää, joten on syytä olettaa, että tietokantataulujenkin lopullinen määrä valmiissa sovelluksessa on nykyistä suurempi.

Sovelluksen runko siis toimii hyvin eikä rikkinäisyyksiä tullut vastaan. Toimintalogiikka on selkeä ja mielelläni olisin kokeillut muitakin toimintoja. Jotain listauksia esimerkiksi suosituimmista makeisista voisi tarjota käyttäjille, mutta tässä vaiheessa kaikki näyttää toimivan hyvin ja olevan helposti ymmärrettävässä muodossa. Tästä on hyvä jatkaa, kun kurssikin on vasta vähitellen puolivälissä.

**Comment by tuukkalai** [comment]
Listattuna tehtäviä lisäyksiä (ja toimivia osia) sovellukseen:
- [x] Saman käyttäjätunnuksen luominen kahdesti ei onnistunut
- [x] salasanan tarkistus toimi
- [x] Makeisten lisääminen tietokantaan edellyttää kaikkien tietojen antamista
- [ ] poistaa makeisia
- [ ] poista käyttäjätili
- [ ] näytön skaalautuvuus kännykän ruudulta kuitenkin jättää vähän toivomisen varaa, kun näytön ollessa pystyasennossa päivyri pitää jokaisen päivämäärän näyttämistä tärkeämpänä kuin varsinaisia kuvaajia
- [ ] kännykällä näytön ollessa vaaka-asennossa päivämäärävalintaruutu ei näy kokonaisuudessaan
- [ ] Mielenkiintoisia lisätoimintoja nykyiseen versioon olisivat tiedot siitä, mistä makeisten määrä koostuu
- [ ] historiatietojen tutkiminen pidemmältä ajalta

Osa näistä on jo toteutettu, osa on työn alla.
