### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by blakaut** [tuukkalai/CandyTracker#2]
Sovelluksen ulkoasu on hyvin intuitiivinen ja toteutetut osat näyttävät toimivan tarkoituksiensa mukaisesti. HTML näyttää omaan (harjaantumattomaan) silmääni hyvin toteutetulta ja pidän siitä, kuinka Jinjaa on hyödynnetty modulaarisuuden luomiseksi. Muutenkin koodi on helppolukuista, joskin sitä ehkä voisi jäsennellä kommenttien avulla.

Tekstikentät voisivat valvoa syötteitä hieman tarkemmin. Esimerkiksi käyttäjätunnukseksi ja salasanaksi käy välilyönti tai sarja välilyöntejä ja makeislistaan on mahdollista lisätä makeisia, joiden paino tai sokeripitoisuus on negatiivinen.

Polls-toimintoa ei mainita README.md-dokumentissa, joten en osaa sanoa, kuuluuko se tarkoitettuun lopputuotteeseen. Mikäli sen on tarkoitus jäädä toimivaksi osaksi sivua, sen toiminnan voisi siirtää omaan luokaansa routes.py:ssä olemisen sijaan.

Sisäänkirjautuessa määritellään session["username"], jota en huomaa käytettävän missään. Samalla määriteltyjä sessions["user_id"]:tä ja sessions["tokenc"]:tä käytetään puolestaan oikein vastuullisesti.

**Comment by tuukkalai** [comment]
Listattuna issuen pohjalta nousseet lisäykset sovellukseen:
- [ ] koodin jäsentely kommenttien avulla
- [ ] käyttäjätunnukseksi ja salasanaksi käy välilyönti tai sarja välilyöntejä
- [ ] makeislistaan on mahdollista lisätä makeisia, joiden paino tai sokeripitoisuus on negatiivinen

Polls-toiminto on mahdollisesti tulossa liitettynä ryhmien toimintoihin. Tullessaan sijoitan sen omaan luokkaansa.

Sisäänkirjautuessa määritelty session["username"] on käytössä ainoastaan navigaatiopalkissa näyttämässä sisäänkirjautuneen käyttäjän käyttäjänimen.

Kiitos kommenteista!
